Read config file for setting up CIS connection
metal-toolbox/alloy pull request #198
Opened 2024-03-24 23:36 UTC by Alva8756

2024-03-25 14:59 UTC, DoctorVin requested changes

2024-03-25 14:59 UTC, DoctorVin commented on cmd/lean/config.go
I see where you're going here and it's a decent start, but Alloy runs both `inband` and `outofband` and we will need to inject the configuration for CIS into the `inband` execution. Doing inventory `inband` is basically a `docker run` so passing things by environment variable is probably the best way.

2024-03-25 14:59 UTC, DoctorVin commented on cmd/lean/helpers.go
We should add this to alloy's existing configuration file management. Take a look at `internal/app/config.go`

2024-03-25 14:59 UTC, DoctorVin commented on cmd/lean/lean.go
I created `lean.go` to do some experiments in alloy without smashing the existing code, but we should start planning how to move all this into `cmd/inband.go` and `cmd/outofband.go`.

2024-03-25 16:57 UTC, Alva8756 commented on cmd/lean/config.go
Do you mean we should support parsing env and override configs? I can add them in a follow up PR.

2024-03-25 17:04 UTC, Alva8756 commented on cmd/lean/helpers.go
Do you mean we move both `cmd/lean/helpers.go` and `cmd/lean/config.go` into `internal/app/helper.go` and `internal/app/config.go`

2024-03-25 17:20 UTC, Alva8756 commented on cmd/lean/config.go
> +	EndpointURL          *url.URL
Good catch, deleted the `EndpointURL`.

2024-03-26 05:58 UTC, Alva8756 commented on cmd/lean/lean.go
Since we are moving some functionality to CIS, it sounds we can delete some codes in Alloy.

It looks we still need to keep nats. We need to delete some functions related to inventory comparison.

I'll make a draft for outbound.go

2024-03-27 21:35 UTC, DoctorVin requested changes

2024-03-29 04:24 UTC, Alva8756 commented on internal/app/config.go
> +	ComponentInventory *ComponentInventoryConfig `mapstructure:"component_inventory"`
Thanks Vince!
Yes it is the client setup for CIS.
I rename it to `ComponentInventoryAPIOptions` which is similar to ConditionOrc

2024-04-01 16:49 UTC, merged